### ISSUE TITLE
daisy202-to-epub3: whenever a epub:textref attribute is added to a SMIL, a "attribute-value" attribute with the same value is added

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-scripts#75] opened 2015-01-22 14:30 UTC
For instance:

``` xml
<seq xmlns:epub="http://www.idpf.org/2007/ops" id="mo1_seq278" epub:textref="content.html#dtb824" attribute-value="content.xhtml#dtb824">
```

`attribute-value` is an option on `p:add-attribute` so there's probably a bug with how that step is used to add the `epub:textref`.

**Comment by bertfrees** [comment] 2017-04-13 15:29
@josteinaj I'm having a hard time figuring out from the code (mediaoverlay-utils + daisy202-to-epub3) when a epub:textref would be added to a SMIL. Can you give me a hint?

**Comment by josteinaj** [comment] 2017-04-18 12:08
according to find+grep, these are the files where a textref is added:

- ./modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/create-mediaoverlay.xsl
- ./modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/prepare-mo-for-join.xsl
- ./modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/conditionally-join-toplevel-seq-with-body.xsl
- ./modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/resolve-relative-uris.xsl
- ./modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/join.xsl

I think the problem might be in ./modules/scripts/daisy202-to-epub3/src/main/resources/xml/convert/media-overlay.xpl though. I'm guessing this:

```xml
<xsl:attribute name="attribute-value" select="replace(@epub:textref,'^(.+)\.[^\.]*#(.*)$','$1.xhtml#$2')"/>
```

should've been this:
```xml
<xsl:attribute name="epub:textref" select="replace(@epub:textref,'^(.+)\.[^\.]*#(.*)$','$1.xhtml#$2')"/>
```

**Comment by bertfrees** [comment] 2017-04-18 12:15
Yes that's probably it. But I hadn't started looking for the bug yet. I'm still trying to find a test case that demonstrates the bug. I don't know what my input has to be in order to get a epub:textref in the output.

**Comment by josteinaj** [comment] 2017-04-18 12:27
modules/scripts-utils/mediaoverlay-utils/src/main/resources/xml/conditionally-join-toplevel-seq-with-body.xsl seems to have an error as well, I'm guessing that's the problem:

```xml
<xsl:if test="mo:body/mo:seq/@epub:type">
    <xsl:attribute name="epub:textref" select="mo:body/mo:seq/@epub:type"/>
</xsl:if>
```

`epub:textref` here should've been `epub:type`.

**Comment by bertfrees** [comment] 2017-04-24 13:40
OK I found out that in `resolve-relative-uris.xsl`, `@epub:textref` attributes are created from `@src` attributes on `seq`, and in `rearrange.xsl`, `seq` elements with `@src` are created for elements in a content document with `@id` that don't have a corresponding `smil:text` element but do have children with a corresponding `smil:text` element.

This way I could reproduce the bug.

**Comment by bertfrees** [comment] 2017-06-13 18:44
Fixed by https://github.com/daisy/pipeline-scripts/pull/104

**Closed by bertfrees** 2017-06-13 18:44 UTC
Labels: 2 - In Progress, bug

**Comment by josteinaj** [comment] 2017-11-22 13:04
We're getting this error in daisy202-to-epub3 now.

Version 1.2.1 of the script was released in ff94d64800f641c82553fb84138320e74fd27120. 

```
➜  pipeline-scripts git:(master) git show master | head -n 1
commit fc36ae398dd0d620d267b760c54a359e8065d345
➜  pipeline-scripts git:(master) git log --oneline ff94d64800f641c82553fb84138320e74fd27120..HEAD daisy202-to-epub3 | cat
f7a2abe daisy202-to-epub3: fix issues #75 and #76
c3d96c7 daisy202-to-epub3: add a test for issues #75 and #76
0e1bab7 Fix issue #74
83012c8 Add a test for issue #74: smil references inside links should be removed
3207018 Fix daisy202-to-epub3 tests and run with modules-test-helper
46d8a2f [maven-release-plugin] prepare for next development iteration
```

So it seems that the patches for this issue haven't been released yet?

**Comment by bertfrees** [comment] 2017-11-22 13:06
Yes, Romain just found out that I didn't release the scripts due to a stupid mistake. I'm planning to make a new release soon.

**Comment by josteinaj** [comment] 2017-11-22 13:16
Ok. I'll try switching temporarily to the SNAPSHOT version for now.

**Comment by bertfrees** [comment] 2017-11-22 17:59
If I have staged the release would you be willing test it?

**Comment by josteinaj** [comment] 2017-11-23 10:44
Yes, sure.

**Comment by josteinaj** [comment] 2017-11-24 13:41
I just noticed that the same error also occurs with epub3-to-daisy202 v1.1.1, so a new release of that script is also necessary.

**Comment by bertfrees** [comment] 2017-11-28 15:48
@josteinaj I have staged the release: https://github.com/daisy/pipeline-assembly/pull/146.

**Comment by josteinaj** [comment] 2017-11-29 11:51
1. Downloaded linux version of v1.10.2 from DP2 homepage, and upgraded to v1.10.3 using updater.

2. Tried reproducing issues

- daisy202-to-epub3:
    - daisy/pipeline-scripts#74: could not reproduce in v1.10.3, I suppose it was fixed in an earlier release
    - daisy/pipeline-scripts#75: can reproduce in v1.10.3
    - daisy/pipeline-scripts#76: can reproduce in v1.10.3
- epub3-to-daisy202:
    - daisy/pipeline-scripts#100: (`Unexpected step name: px:unzip-fileset`) can reproduce in v1.10.3

3. Upgraded to the staged v1.10.4 as follows:

- deleted: `…daisy202-to-epub3-1.2.1.jar`, `…epub3-to-daisy202-1.1.1.jar` and `…mediaoverlay-utils-1.1.1.jar `
- added from sonatype staging: `daisy202-to-epub3-1.2.2.jar`, `epub3-to-daisy202-1.1.2.jar` and `mediaoverlay-utils-1.1.2.jar`

4. Tried reproducing issues

- daisy202-to-epub3:
    - daisy/pipeline-scripts#74: still works fine
    - daisy/pipeline-scripts#75: can't reproduce. fixed.
    - daisy/pipeline-scripts#76: can't reproduce. fixed.
- epub3-to-daisy202:
    - daisy/pipeline-scripts#100: (`Unexpected step name: px:unzip-fileset`) could not reproduce, so this issue is fixed. However, the result is not valid: daisy/pipeline-scripts#116
    - found a couple of issues in the webui (although that's not directly relevant for the v1.10.4 release): daisy/pipeline-webui#120 daisy/pipeline-webui#121

So the staged v1.10.4 release fixes daisy202-to-epub3 but not epub3-to-daisy202.

**Comment by bertfrees** [comment] 2017-11-29 12:06
@josteinaj Thanks! Maybe next time it's better to update to the staged release via the updater as well. You would need to set the descriptor URL to https://raw.githubusercontent.com/daisy/pipeline-assembly/rd-1.10.4/. I think that would work.

The #116 bug, that's probably an older one, right? Not a regression in 1.10.4?

**Comment by josteinaj** [comment] 2017-11-29 12:48
Yeah I was wondering if I could use the updater but wasn't sure how. Will try that next time.

#116 is not a regression no. It must just be the case that nobody have been using that script until now. Maybe it was introduced in a previous release, I don't know.
